
stages:
  - setup
  - test

setup:
  stage: setup
  tags:
    - all
  script:
    - apt-get update -qy
    - apt-get install -y libglfw3 libglfw3-dev ocl-icd-libopencl1 ocl-icd-opencl-dev
  artifacts:
    paths:
      - ./libs
    expire_in: 1 week

test:
  stage: test
  tags:
    - all
  script:
    - echo "Testing in progress..."
  environment: production
