
stages:
  - build
  - test

build:
  stage: build
  tags:
    - all
  script:
    - apt-get update -qy
    - apt-get install -y libglfw3 libglfw3-dev ocl-icd-libopencl1 ocl-icd-opencl-dev build-essential cmake git googletest
    - cmake -B build
    - cmake --build build
  artifacts:
    paths:
      - ./libs
    expire_in: 1 week

GoogleTests:
  stage: test
  tags:
    - all
  script:
    - echo "Testing in progress..."
    - .\build\tests\TestApp_test_run   

  environment: production
