
stages:
  - build
  - test

build:
  stage: build
  tags:
    - all
  script:
    - apt-get update -qy
    - apt-get install -y libglfw3 libglfw3-dev ocl-icd-libopencl1 ocl-icd-opencl-dev build-essential cmake git googletest libgtest-dev opencl-c-headers opencl-clhpp-headers clinfo
    - clinfo
    - echo "Building in progress..."
    - cmake -B build -G "Unix Makefiles"
    - cmake --build build
  cache:
    paths:
      - build/

GoogleTests:
  stage: test
  
  tags:
    - all
  script:
    - echo "Testing in progress..."
    - .\\build\\tests\\TachyonEngine_test 
  allow_failure: true
  environment: production
  dependencies:
    - build
